# Generated by Django 4.2 on 2024-04-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='todo')),
                ('completed', models.BooleanField(default=False)),
                ('expired', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'todos',
                'ordering': ['expired'],
            },
        ),
    ]
